services:
  nodejs:
    image: ${NODE_IMAGE}
    ports:
      - "8080:80"
    volumes:
      - "./code:/app"
  postgres:
    image: ${POSTGRES_IMAGE}
    volumes:
      - "./db/mount:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    # command: "export PGPASSWORD=${DB_PASS}; psql -U ${DB_USER} -h localhost -c 'create database auth;'"
  kratos:
    image: kratos-debian:1.2.0
    build: .
    command:
      - '/usr/local/bin/kratos --help'
      #- "kratos serve -c /home/kratos/kratos.yml"
    ports:
      - '${ORY_ADMIN_PORT}:${ORY_ADMIN_PORT}'
      - '${ORY_PUBLIC_PORT}:${ORY_PUBLIC_PORT}'
    depends_on:
      - postgres
      - nodejs